export const SET_PRODUCTS = "SET_PRODUCTS";
export const DETAILS_PRODUCT = "DETAILS_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const CATEGORY_PRODUCTS = "CATEGORY_PRODUCTS";
export const QUANTITY_INCREMENT = "QUANTITY_INCREMENT";
export const QUANTITY_DECREMENT = "QUANTITY_DECREMENT";
export const TOP_PRODUCTS = "TOP_PRODUCTS";
